name: Simple C++ Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install SQLite
      run: sudo apt-get install -y libsqlite3-dev

    - name: Compile Code
      run: |
        g++ -std=c++17 -O2 -Wall -Wextra \
          -Isrc -Ivendor/SQLiteCpp/include \
          src/main.cpp \
          src/models/Item.cpp src/models/Inventory.cpp \
          src/models/Customer.cpp \
          src/storage/Storage.cpp src/storage/Receipt.cpp \
          src/storage/CustomerStorage.cpp \
          src/controllers/WmsControllers.cpp \
          src/reports/ReportEngine.cpp \
          src/output/output.cpp src/cli/cli.cpp \
          vendor/SQLiteCpp/src/Backup.cpp \
          vendor/SQLiteCpp/src/Column.cpp \
          vendor/SQLiteCpp/src/Database.cpp \
          vendor/SQLiteCpp/src/Exception.cpp \
          vendor/SQLiteCpp/src/Savepoint.cpp \
          vendor/SQLiteCpp/src/Statement.cpp \
          vendor/SQLiteCpp/src/Transaction.cpp \
          -lsqlite3 -lpthread -ldl \
          -o wms
